In [1]:
import tensorflow as tf

In [3]:
vector_tf = tf.constant([1,2,3])

In [5]:
print(vector_tf)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [2]:
arr_tf = tf.random.normal((2,2,2,2), mean=1, stddev=2.5)

In [3]:
arr_tf

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[-0.6751342 ,  2.554162  ],
         [-3.070578  ,  2.0638962 ]],

        [[ 5.127546  ,  1.5437328 ],
         [ 3.7998395 ,  5.9600034 ]]],


       [[[-2.7342646 ,  5.0509777 ],
         [ 3.0053678 ,  1.652204  ]],

        [[ 2.1227973 ,  6.074685  ],
         [ 1.8384795 ,  0.16559786]]]], dtype=float32)>

In [5]:
arr_tf.numpy().mean()

2.154957

In [8]:
arr_tf.numpy().std()

2.6759062

In [11]:
arr_tf = tf.random.random(2,2,2,2)

AttributeError: module 'tensorflow._api.v2.random' has no attribute 'random'

In [18]:
coef = tf.Variable([ [1,1,1,1], [2,3,0,-1], [-3, 4, 1, 2], [1, 2, -1, 1] ], dtype=tf.float32)
y = tf.Variable([ [13],[-1], [10],[1] ], dtype=tf.float32)

inv_coef = tf.linalg.inv(coef)
inv_coef

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 2.77777791e-01,  5.55555224e-02, -1.66666672e-01,
         1.11111104e-01],
       [-7.40740746e-02,  1.85185164e-01,  1.11111104e-01,
         3.70370336e-02],
       [ 4.62962925e-01,  9.25926119e-02,  5.55555634e-02,
        -4.81481493e-01],
       [ 3.33333343e-01, -3.33333343e-01, -9.93410776e-09,
         3.33333343e-01]], dtype=float32)>

In [19]:
tf.matmul(inv_coef, y)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 2.0000000e+00],
       [-1.1920929e-07],
       [ 5.9999995e+00],
       [ 5.0000000e+00]], dtype=float32)>

In [22]:
w = tf.Variable([ [0.5, 1, -1.2] ], dtype=tf.float32)
x = tf.Variable([ [.2, 1, .5] ], dtype=tf.float32)

tf.matmul(w,inv_x)

InvalidArgumentError: {{function_node __wrapped__MatrixInverse_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input matrix must be square. [Op:MatrixInverse]