<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [2]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

##### Creating a 1 D array of ones

In [3]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [4]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [5]:
arr = np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [6]:
arr.dtype

dtype('int64')

##### Creating a 5  x 3 array of ones


In [6]:
ones = np.ones((5,3), dtype=int, order='F')
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
ones[1][0] = 5
np.sum(ones, axis = 0)

array([9, 5, 5])

##### Creating array of zeros

In [8]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [9]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
# Create a list of integers range between 1 to 5.
list(range(1,5))

[1, 2, 3, 4]

In [13]:
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [20]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [21]:
np.random.randint(2, size=10)

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [24]:
np.random.randint(3,5, size=10)

array([3, 3, 3, 3, 4, 3, 3, 3, 3, 4])

##### 2D Array of random numbers 


In [25]:
np.random.random([3,4])

array([[0.37947795, 0.50446351, 0.76204337, 0.23268129],
       [0.49530063, 0.37298231, 0.17830691, 0.9400508 ],
       [0.18746889, 0.99395211, 0.03729134, 0.16021317]])

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [10]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [5]:
twos = np.full((3,4), 2, dtype=int)

In [6]:
more_twos = np.tile(twos, 3)

In [8]:
more_twos

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [15]:
np.eye(3,3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
np.random.random((3,4))*10

array([[4.91555038, 8.87774766, 9.99765174, 8.90376734],
       [2.64755536, 3.71092892, 7.5723425 , 1.06567484],
       [8.98890942, 4.49291369, 2.1659336 , 1.98333949]])

In [23]:
ones = np.ones((4,4))

In [24]:
ones[1:3,1:3]

array([[1., 1.],
       [1., 1.]])

In [10]:
x = np.random.randint(1, 10, 20)

In [12]:
x.reshape((4,5))

array([[4, 2, 2, 4, 5],
       [7, 6, 1, 4, 1],
       [1, 8, 6, 1, 1],
       [7, 7, 6, 1, 6]])